apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${{ secrets.CONTACT_EMAIL }}
    privateKeySecretRef:
      name: athena-letsencrypt-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
