apiVersion: v1
kind: Service
metadata:
  name: codbex-athena
  namespace: dev
  labels:
    app: codbex-athena
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: codbex-athena
  type: ClusterIP
