name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  modules:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-athena
      packages-build: codbex-athena
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-athena - ${{ inputs.release-version }}
  
        Warehouse Management - Dashboard
  
        ## Installation
  
        ```
        npm install @codbex/codbex-athena@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-athena/gen/](http://localhost:80/services/web/codbex-athena/gen/) - Admin Panel
    secrets: inherit